using Portal.Shared.DTO.Quote;

namespace Portal.Server.Views.ViewModels;

public class QuoteAcceptanceModel
{
    /// <summary>
    /// The token is a unique identifier for the quote acceptance process. 
    /// It is used to securely identify and validate the quote acceptance request. 
    /// The token ensures that only authorized users can access the quote acceptance page and perform the necessary actions.
    /// It is typically generated when a quote is created and sent to the customer, 
    /// allowing them to accept or reject the quote through a secure link containing the token.
    /// </summary>
    public required string Token { get; set; }

    /// <summary>
    /// The Url where the user can accept the quote. This URL is typically generated by the server and sent to the customer via email or other communication channels. 
    /// When the customer clicks on the acceptance link, they are directed to this URL, which allows them to review the quote details and confirm their acceptance. 
    /// The URL may contain query parameters, such as the token, to ensure that the acceptance process is secure and properly linked to the specific quote.
    /// </summary>
    public required string AcceptQuoteUrl { get; set; }

    /// <summary>
    /// The details of the quote
    /// </summary>
    public required QuoteDetailsDto Details { get; set; }
}
